Zrawberry2020/Zrawberry2020/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from .sitemaps import BlogSitemap

sitemaps = {
    'blog': BlogSitemap,
}


urlpatterns = [
    path('', TemplateView.as_view(template_name='common/index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
    path('navigation/', include('navigation.urls', namespace='navigation')),
    path('images/', include('image.urls', namespace='images')),
    # robots, sitemap
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    # sitemaps should be a dictionary that maps a short section label (e.g., blog or news) to its Sitemap class
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Zrawberry2020/article/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

from . import views

app_name = "article"

urlpatterns = [
    # 后台
    path('article-column/', views.article_column, name="article_column"),
    path('article-post/', views.ArticlePostView.as_view(), name="article_post"),
    path('article-list/', views.article_list, name="article_list"),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
            views.article_detail, name="article_detail"),

    # 后台功能
    path('del-article/', views.del_article, name="del_article"),
    path('delete-column/', views.delete_article_column, name="del_article_column"),
    path('redit-article/<int:pk>/<slug:slug>/', views.ArticleEditView.as_view(), name="redit_article"),
    path('rename-column/', views.rename_article_column, name="rename_article_column"),

    # 前台
    path('', views.article_titles, name="article_titles"),
    path('timeline/', views.TimelineView.as_view(), name="timeline"),
    path('dessert/', views.dessert, name="dessert"),
    path('<column_name>/', views.article_titles, name="article_column"),
    path('article-content/<int:aid>/<slug:slug>/', views.article_content, name="article_content"),
]

Zrawberry2020/image/urls.py
from django.urls import path, re_path
from . import views

app_name = "images"

urlpatterns = [
    path('', views.PicList.as_view(), name='pic_list'),
    path('upload-modelform/', views.picture_modelform_upload, name='model_form_upload'),
    path('upload-ajax/', views.picture_ajax_upload, name='ajax_upload'),
    path('delete-ajax/', views.picture_delete, name='pic_delete'),
    re_path('pic/upload/$', views.PicUpload.as_view(), name='pic_upload'),
    re_path('pic/(?P<pk>\d+)/$', views.PicDetail.as_view(), name='pic_detail'),
]

Zrawberry2020/article/models.py
from django.utils import timezone
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from slugify import slugify


class ArticleColumn(models.Model):
    """文章栏目"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article_column')
    column = models.CharField(max_length=50)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):
    tag = models.CharField(max_length=30, blank=False)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.tag


class ArticlePost(models.Model):
    SHOW_TYPE = [('0', '文章'), ('1', '甜品站'), ('2', '特殊页面')]
    # author, title, slug, column, body, created, updated,viewed, showtype,targetuser,tags

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="article")
    title = models.CharField(verbose_name="标题", max_length=200)
    column = models.ForeignKey(ArticleColumn, verbose_name="栏目", on_delete=models.PROTECT,
                               related_name="article", null=True, blank=True)
    tags = models.ManyToManyField(ArticleTag, verbose_name="标签", blank=True, related_name="Articles")
    body = models.TextField(verbose_name="正文")
    showtype = models.CharField(verbose_name="展示类型", max_length=10, choices=SHOW_TYPE, default='0')
    targetuser = models.ManyToManyField(User, verbose_name="目标用户(甜品站)",
                                        related_name="dessert", blank=True)

    slug = models.SlugField(max_length=500)
    created = models.DateTimeField(default=timezone.now)  # 时区的发布时间
    updated = models.DateTimeField(default=timezone.now)
    viewed = models.IntegerField(default=0)

    # users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)
    # article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True)

    class Meta:
        ordering = ("-updated",)
        index_together = (('id', 'slug'),)  # 使用两个字段建立索引 加快读取速度
        permissions = (
            ("get_dessert", "可以进入甜品站，查看以自己为对象的文章。"),
            ("post_article", "发布或者编辑文章"),
        )

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        """重写save方法"""
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        # 后台的文章页面
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        return reverse("article:article_content", args=[self.id, self.slug])

    @classmethod
    def get_special_page(cls):
        pages = cls.objects.filter(showtype='2')
        return {'special_page': pages}


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, on_delete=models.CASCADE, related_name="comments")
    commentator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    body = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "{0}在{1}中发表".format(self.commentator.username, self.article)


class Navlink(models.Model):
    name = models.CharField(max_length=12, verbose_name="链接名")
    link = models.CharField(max_length=100, default='/article/', verbose_name="链接")
    show = models.BooleanField(default=True, verbose_name="展示")

    def __str__(self):
        return self.name

    @classmethod
    def get_nav_link(cls):
        nav_links = cls.objects.filter(show=True)
        return {'nav_links': nav_links}

Zrawberry2020/article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column", )


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'showtype', 'body')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)

Zrawberry2020/article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.utils import timezone

from .models import ArticleColumn, ArticlePost, ArticleTag, Navlink
from .forms import ArticleColumnForm, ArticlePostForm, CommentForm


def get_common_context(context):
    context.update(ArticlePost.get_special_page())
    context.update(Navlink.get_nav_link())

# == 文章栏目 ==
# @permission_required()
@login_required
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        context = {
            "columns": columns,
            "column_form": column_form,
            "column": 'active',
        }
        get_common_context(context)
        return render(request, "article/column/article_column.html", context=context)

    elif request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        # 检查是否已经存在该栏目
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")


@login_required()
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required()
@require_POST
@csrf_exempt
def delete_article_column(request):
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


# == 文章编辑 ==
class ArticlePostView(CreateView):
    """文章发布"""
    model = ArticlePost
    # title, column, body, showtype,targetuser
    fields = ['title', 'column', 'showtype', 'targetuser', 'body', 'tags']
    template_name = 'article/column/article_post.html'

    def form_valid(self, form):
        if self.request.user.has_perm('article.post_article'):
            # 只有拥有发布权限才指定 user
            form.instance.author = self.request.user
        else:
            raise Http404("Poll does not exist")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ArticlePostView, self).get_context_data(**kwargs)
        context['post'] = 'active'
        get_common_context(context)
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ArticlePostView, self).dispatch(request, *args, **kwargs)


class ArticleEditView(UpdateView):
    """文章编辑"""
    model = ArticlePost
    fields = ['title', 'column', 'showtype', 'targetuser', 'body', 'tags']
    template_name = 'article/column/article_post.html'
    context_object_name = 'article_form'
    # template_name_suffix = '_update_form'

    def form_valid(self, form):
        form.instance.updated = timezone.now()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ArticleEditView, self).get_context_data(**kwargs)
        context['post'] = 'active'
        get_common_context(context)
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ArticleEditView, self).dispatch(request, *args, **kwargs)


@login_required()
def article_list(request):
    # articles = ArticlePost.objects.filter(author=request.user)
    # return render(request, "article/column/article_list.html", {"articles": articles})
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 14)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    context = {
        "articles": articles,
        "page_obj": current_page,
        "list": 'active',
    }
    get_common_context(context)
    return render(request, "article/column/article_list.html", context=context)


@login_required()
def article_detail(request, id, slug):
    """从链接中获取文章信息"""
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    context = {"article":article}
    get_common_context(context)
    return render(request, "article/column/article_detail.html", context=context)


@login_required()
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


def article_titles(request, column_name=None):
    # articles = User.objects.get(id=1).article.filter(showtype='0')  # 只展示Zachary的
    articles = ArticlePost.objects.filter(showtype='0')
    if request.GET.get('search', None):
        articles = articles.filter(title__contains=request.GET['search'])
    # 获取文章列表
    if column_name:
        try:
            # articles_title = ArticleColumn.objects.get(column=column_name).article.all()
            # articles_title = ArticleColumn.objects.get(column=column_name).article.all()
            column = ArticleColumn.objects.get(column=column_name)
            articles_title = articles.filter(column=column)
        except:
            return HttpResponseRedirect(reverse('article:article_titles'))
    else:
        articles_title = articles

    # 文章分页
    paginator = Paginator(articles_title, 3)
    page_number = request.GET.get('page')
    # try:
    #     current_page = paginator.page(page_number)
    #     articles = current_page.object_list
    try:
        page_obj = paginator.get_page(page_number)
        articles = page_obj.object_list
    except PageNotAnInteger:
        page_obj = paginator.get_page(1)
        articles = page_obj.object_list
    except EmptyPage:
        page_obj = paginator.get_page(paginator.num_pages)
        articles = page_obj.object_list

    # 获取分类列表
    # columns = User.objects.get(id=1).article_column.all()
    columns = ArticleColumn.objects.all()
    context = {
        "articles": articles,
        "page_obj": page_obj,
        "columns": columns,
        "search": request.GET.get('search', None),
    }
    if column_name:
        context['active'] = column_name
    get_common_context(context)
    return render(request, "article/front/article_titles.html", context=context)


def article_content(request, aid, slug):
    """文章内容"""
    article = get_object_or_404(ArticlePost, id=aid, slug=slug)
    context = {
        "article": article,
    }
    # 特殊类型文章
    if article.showtype == '1':
        if request.user == 'AnonymousUser' or not request.user.has_perm('article.get_dessert'):
            return HttpResponseRedirect(reverse('account:user_login')+'?next='+request.path)
        if request.method == "POST":  # 仅特殊文章可以评论
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.article = article
                new_comment.commentator = request.user
                new_comment.save()
            else:
                return render(request, "404.html")
        else:
            comment_form = CommentForm()

        context['form'] = comment_form
        context['comment'] = True

    if request.user.id != 1:
        article.viewed += 1
    article.save()
    get_common_context(context)
    return render(request, "article/front/article_content.html", context=context)


@login_required
@permission_required('article.get_dessert', raise_exception=True)
def dessert(request):
    """甜品站titles"""
    # articles = User.objects.get(id=1).article.filter(showtype='1')
    articles = ArticlePost.objects.filter(showtype='1')

    articles_title = articles.filter(targetuser=request.user)
    paginator = Paginator(articles_title, 3)
    page = request.GET.get('page')

    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    # 获取分类列表
    # columns = User.objects.get(id=1).article_column.all()
    columns = ArticleColumn.objects.all()
    context = {
        "articles": articles,
        "page_obj": current_page,
        "columns": columns,
    }
    get_common_context(context)
    return render(request, "article/front/article_titles.html", context=context)


class TimelineView(ListView):
    model = ArticlePost
    queryset = ArticlePost.objects.filter(showtype='0').order_by("-created")
    template_name = "article/front/article_timeline.html"
    context_object_name = 'articles'

    def get_context_data(self, **kwargs):
        context = super(TimelineView, self).get_context_data(**kwargs)

Zrawberry2020/templates/article/column/article_column.html
{% extends "common/back_base.html" %}
{% load static %}

{% block title %}文章栏目{% endblock %}

{% block content %}
    <div>
        <h3>栏目</h3>
        <table class="table table-hover">
            <tr>
                <td>序号</td>
                <td>栏目名称</td>
                <td>操作</td>
            </tr>
            {% for column in columns %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ column.column }}</td>
                    <td>
                        <a name="edit" href="javascript:" onclick="edit_column(this, {{ column.id }})">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a name="delete" href="javascript:" onclick="del_column(this, {{ column.id }})">
                            <span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span>
                        </a>
                    </td>
                </tr>
            {% empty %}
                <p>还没有设置栏目，太懒了。</p>
            {% endfor %}
        </table>
        <p><!--button class="btn btn-primary">add column</button-->
            <button id="add_column" onclick="add_column()" class="btn btn-primary">添加栏目</button>
        </p>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
    <script type="text/javascript" src="{% static "js/layer.js" %}"></script>
    <script type="text/javascript">
        function add_column() {
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "新增栏目",
                content: '<div class="text-center" style="margin-top:20px"> <p> 请输入新的栏目名称</p> <p>{{ column_form.column }}</p></div > ',
                btn: ['确定', '取消'],
                yes: function (index, layero) {
                    column_name = $('#id_column').val();
                    $.ajax({
                        url: '{% url "article:article_column" %}',
                        type: 'POST',
                        data: {"column": column_name},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("添加成功");
                            } else {
                                layer.msg("此栏目已有，请更换名称")
                            }
                        },
                    });
                },
                btn2: function (index, layero) {
                    layer.close(index);
                }
            });
        }

        function edit_column(the, column_id) {
            var name = $(the).parents("tr").children("td").eq(1).text();
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "编辑栏目",
                content: '<div class="text-center" style="margin-top:20px"> <p>请编辑的栏目名称</p><p><input type="text" id="new_name" value="' + name + '"></p> </div>',
                btn: ['确定', '取消'],
                yes: function (index, layero) {
                    new_name = $("#new_name").val();
                    $.ajax({
                        url: "{% url 'article:rename_article_column' %}",
                        type: "POST",
                        data: {"column_id": column_id, "column_name": new_name},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("good");
                            } else {
                                layer.msg("新的名称没有保存,修改失败。")
                            }
                        },
                    });
                },
            });
        }

        function del_column(the, column_id) {
            var name = $(the).parents("tr").children("td").eq(1).text();
            layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "删除栏目",
                content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除{' + name + '}栏目</p> </div>',
                btn: ['确定', '取消'], yes: function () {
                    $.ajax({
                        url: '{% url "article:del_article_column" %}',
                        type: "POST",
                        data: {"column_id": column_id},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("has been deleted.");
                            } else {
                                layer.msg("删除失败");
                            }
                        },
                    })
                },
            });
        }
    </script>
{% endblock %}

Zrawberry2020/templates/article/column/article_post.html
{% extends "common/back_base.html" %}
{% load static %}
{% load account_extras %}
{% block title %}文章栏目{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">


    <form class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="col-sm-6">
            <div class="col-xs-12 input-group">
                <label for="id_title">标题</label>
                {#            <div class="col-md-2"><span>标题:</span></div>#}
                {{ form.title|addclass:"form-control" }}
            </div>
            <div class="col-xs-12 input-group">
                <label for="id_column">栏目</label>
                {{ form.column|addclass:"form-control" }}
            </div>
            <div class="col-xs-12 input-group">
                <label for="id_showtype">展示类型</label>
                {{ form.showtype|addclass:"form-control" }}
            </div>
        </div>
        <div class="col-sm-6">
            <div class="col-xs-12 input-group">
                <label for="id_targetuser">甜品站目标用户</label>
                {{ form.targetuser|addclass:"form-control" }}
            </div>
            <div class="col-xs-12 input-group">
                <label for="id_tags">文章标签</label>
                {{ form.tags|addclass:"form-control" }}
            </div>
        </div>
        {#        <div class="row" style="margin-top: 10px;">#}
        {#            <div class="col-md-2 text-right"><span>文章标签:</span></div> #}
        {#            <div class="col-md-10 text-left">#}
        {#                {% for tag in article_tags %} #}
        {#                <label class="checkbox-inline">#}
        {#                    <input class="tagcheckbox" type="checkbox" id="{{ tag.id }}" name="article_tag" value="{{ tag.tag }}"> {{ tag.tag }}#}
        {#                </label>#}
        {#                {% empty %}#}
        {#                <p>You have not type tags for articles. Please <a href="{% url 'article:article_tag' %}">input your tags</a></p> #}
        {#                {% endfor %}    #}
        {#            </div>#}
        {#        </div>#}
        <div class="col-md-12 row">
            <div id="editormd">
                {{ form.body }}
            </div>
        </div>
        <div class="row text-center">
            <input type="submit" class="btn btn-primary" value="发布/修改">
        </div>
    </form>

{% endblock %}
{% block javascript %}
    {#    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>#}
    {#<script type="text/javascript" src="{% static 'js/json2.js' %}"></script>#}
    {#    <script type="text/javascript">#}
    {#        function publish_article() {#}
    {#            var title = $("#id_title").val();#}
    {#            var column_id = $("#which_column").val();#}
    {#            var body = $("#id_body").val();#}
    {#            var showtype = $("#id_showtype").val();#}
    {#var article_tags = [];#}
    {#$.each($("input[name='article_tag']:checked"), function(){article_tags.push($(this).val());});#}
    {#            $.ajax({#}
    {#                url: "{% url 'article:article_post' %}",#}
    {#                type: "POST",#}
    {#data: {"title":title, "body":body, "column_id":column_id, "tags":JSON.stringify(article_tags)},#}
    {#                data: {"title": title, "body": body, "column_id": column_id, "showtype": showtype},#}
    {#                success: function (e) {#}
    {#                    if (e == "3") {#}
    {#                        layer.msg("项目名称必须写，不能空。");#}
    {#                    } else if (e == "2") {#}
    {#                        layer.msg("发送失败.");#}
    {#                    } else {#}
    {#                        layer.msg("发送成功");#}
    {#parent.location.href = "{% url 'article:article_list' %}";#}
    {#                        parent.location.href = e;#}
    {#location.reload()#}
    {#                    }#}
    {#                },#}
    {#            });#}
    {#        }#}
    {#    </script>#}

    <script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
    <script type="text/javascript">
        $(function () {
            var editor = editormd("editormd", {
                width: "100%",
                height: 640,
                syncScrolling: "single",
                path: "{% static 'editor/lib/' %}"
            });
        });
    </script>
{% endblock %}

Zrawberry2020/templates/article/column/redit_article.html
{% extends "common/back_base.html" %}
{% load static %}


{% block title %}编辑文章{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% endblock %}

{% block content %}
{{ form }}
    <div>
        <form class="form-horizontal" action="." method="post">{% csrf_token %}
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>标题:</span></div>
                <div class="col-md-10 text-left">{{ this_article_form.title }}</div>
            </div>
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>栏目:</span></div>
                <div class="col-md-10 text-left">
                    <select id="which_column">
                        {% for column in article_columns %}
                            {% if column == this_article_column.column %}
                                <option value="{{ column.id }}"
                                        selected="selected">{{ column.column }} </option>
                            {% else %}
                                <option value="{{ column.id }}">{{ column.column }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row" style="margin-top: 10px;">
                <div id="editormd">
                    <textarea style="display:none;" id="id_body">
{{ article.body }}
                    </textarea>
                </div>
            </div>
            <div class="text-center">
                <input type="button" class="btn btn-primary" value="修改" onclick="redit_article()">
            </div>
        </form>
    </div>
{% endblock %}
{% block javascript %}
    <script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            var editor = editormd("editormd", {
                width: "100%",
                height: 640,
                //syncScrolling : "single",
                path: "{% static 'editor/lib/' %}",
            });
        });

        function redit_article() {
            var title = $("#id_title").val();
            var column_id = $("#which_column").val();
            var body = $("#id_body").val();
            $.ajax({
                {#url: "{% url 'article:redit_article' article.id %}",#}
                type: "POST",
                data: {"title": title, "body": body, "column_id": column_id},
                success: function (e) {
                    if (e == "2") {
                        layer.msg("修改失败");
                    } else {
                        layer.msg("成功");
                        {#location.href = "{% url 'article:article_list' %}";#}
                        location.href = e;
                    }
                },
            });
        }
    </script>
{% endblock %}