Zrawberry2020/Zrawberry2020/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from .sitemaps import BlogSitemap

sitemaps = {
    'blog': BlogSitemap,
}


urlpatterns = [
    path('', TemplateView.as_view(template_name='common/index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
    path('navigation/', include('navigation.urls', namespace='navigation')),
    path('images/', include('image.urls', namespace='images')),
    # robots, sitemap
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    # sitemaps should be a dictionary that maps a short section label (e.g., blog or news) to its Sitemap class
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Zrawberry2020/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='user_login'),
    # path('login/', views.user_login, name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),
    # 修改密码
    path('password-change/',
         auth_views.PasswordChangeView.as_view(
             template_name="account/password_change_form.html",
             success_url="/account/password-change-done/"),
         name='password_change'),
    path('password-change-done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name="account/password_change_done.html", ),
         name='password_change_done'),
    # 重置密码
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name="account/password_reset_form.html",
             email_template_name="account/password_reset_email.html",
             # html_email_template_name="account/password_reset_email.html",
             success_url='/account/password-reset-done/'),
         name='password_reset'),
    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="account/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="account/password_reset_confirm.html",
             success_url='/account/password-reset-complete/'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="account/password_reset_complete.html"),
         name='password_reset_complete'),
    path('my-information/', views.myself, name="my_information"),
    path('edit-my-information/', views.myself_edit, name="edit_my_information"),
    path('my-image/', views.my_image, name="my_image"),
    path('dashboard/', views.dashboard, name="dashboard"),
]

Zrawberry2020/article/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

from . import views

app_name = "article"

urlpatterns = [
    # 后台
    path('article-column/', views.article_column, name="article_column"),
    path('article-post/', views.ArticlePostView.as_view(), name="article_post"),
    path('article-list/', views.article_list, name="article_list"),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
            views.article_detail, name="article_detail"),

    # 后台功能
    path('del-article/', views.del_article, name="del_article"),
    path('delete-column/', views.delete_article_column, name="del_article_column"),
    path('redit-article/<int:pk>/<slug:slug>/', views.ArticleEditView.as_view(), name="redit_article"),
    path('rename-column/', views.rename_article_column, name="rename_article_column"),

    # 前台
    path('', views.article_titles, name="article_titles"),
    path('timeline/', views.TimelineView.as_view(), name="timeline"),
    path('dessert/', views.dessert, name="dessert"),
    path('<column_name>/', views.article_titles, name="article_column"),
    path('article-content/<int:aid>/<slug:slug>/', views.article_content, name="article_content"),
]

Zrawberry2020/image/urls.py
from django.urls import path, re_path
from . import views

app_name = "images"

urlpatterns = [
    path('', views.PicList.as_view(), name='pic_list'),
    path('upload-modelform/', views.picture_modelform_upload, name='model_form_upload'),
    path('upload-ajax/', views.picture_ajax_upload, name='ajax_upload'),
    path('delete-ajax/', views.picture_delete, name='pic_delete'),
    re_path('pic/upload/$', views.PicUpload.as_view(), name='pic_upload'),
    re_path('pic/(?P<pk>\d+)/$', views.PicDetail.as_view(), name='pic_detail'),
]

Zrawberry2020/navigation/urls.py
from django.urls import path

from . import views

app_name = "navigation"

urlpatterns = [
    path('', views.FrontendView.as_view(), name="navigation_index"),
    path('navigation-link/', views.navigation_list, name="navigation_list"),
    path('navigation-box/', views.navigation_box, name="navigation_box"),
]

Zrawberry2020/templates/common/back_base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}仪表盘{% endblock %}- 草莓君的妙妙屋</title>

    <link rel="shortcut icon" href="{% static 'image/favicon2.ico' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/adjust.css' %}">


    {% block css %}{% endblock %}
</head>
<body>
{#{% include 'common/back_header.html' %}#}
{% include 'common/header.html' %}

<div class="container content">
    <div class="col-md-9">
        <div class="whitergba">
            {% block content %}
                <h1>妙妙屋欢迎您的到访</h1>
                <p>你所在的位置：用户后台</p>
                {% if user.is_staff %}
                    <p>您是管理员用户，可以访问 <a href="/admin/">admin</a>后台和<a href="http://bt.zrawberry.com:2020/getin/">宝塔面板</a>。
                    </p>
                {% endif %}
            {% endblock %}
        </div>
    </div>

    <div class="col-md-3">
        {% include 'common/back_leftslider.html' %}
        {% block leftslider %}

        {% endblock %}
    </div>
</div>

{% include 'common/footer.html' %}

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

Zrawberry2020/templates/common/back_header.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'account:dashboard' %}">妙妙屋的仪表盘</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'article:article_titles' %}">文章</a></li>
                {% if special %}
                <li><a href="{% url 'article:dessert' %}">甜品站</a></li>
                {% endif %}
                <li><a href="{% url 'navigation:navigation_index' %}">网址导航</a></li>
                <li><a href="{% url 'navigation:navigation_index' %}">实验室</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown {{ account }}">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'account:dashboard' %}">用户后台</a></li>
                        <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                        <li><a href="{% url 'account:user_logout' %}">退出</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

Zrawberry2020/templates/common/back_leftslider.html
{% if user.is_staff %}
<div class="list-group">
    <h3 class="list-group-item">内容管理</h3>
    <a href="{% url 'article:article_column' %}" class="list-group-item {{ column }}">编辑分类</a>
    <a href="{% url 'article:article_list' %}" class="list-group-item {{ list }}">文章列表</a>
    <a href="{% url 'article:article_post' %}" class="list-group-item {{ post }}">编辑/发布</a>
    <a href="{% url 'images:pic_list' %}" class="list-group-item {{ pic }}">图片列表</a>
</div>
{% endif %}

<div class="list-group">
    <h3 class="list-group-item">网址导航</h3>
    <a href="{% url 'navigation:navigation_box' %}" class="list-group-item {{ boxes }}">网址类型（盒子）</a>
    <a href="{% url 'navigation:navigation_list' %}" class="list-group-item {{ links }}">编辑网址</a>
</div>

Zrawberry2020/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'image/favicon2.ico' %}" type="image/x-icon"/>

    <title>{% block title %}{% endblock %}- 草莓君的妙妙屋</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/adjust.css' %}">
    <style>

    </style>
    {% block css %}{% endblock %}
</head>
<body>
{% include "common/header.html" %}

<div class="container content">
    {% block content %}
    {% endblock %}
</div>

{% include "common/footer.html" %}

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

Zrawberry2020/templates/common/footer.html
{% load static %}

<footer>
    <div class="container text-center navbar-static-bottom" >
        <div class="col-md-6">
            <h4>快刀切草莓君</h4>
            <ul class="list-inline">
                <li class="btn btn-link"><a href="https://weibo.com/Zaaachary" target="_blank">Weibo</a></li>
                <li class="btn btn-link"><a href="https://github.com/Zaaachary" target="_blank">Github</a></li>
                <li class="btn btn-link"><a href="https://www.cnblogs.com/Zaaachary/" target="_blank">BlogCN</a></li>
                <li class="btn btn-link"><a href="https://space.bilibili.com/3337790" target="_blank">BiliBili</a></li>
            </ul>
        </div>
        <div class="col-md-6">
            <h4>友情链接</h4>
            <ul class="list-inline">
                <li class="btn btn-link"><a href="https://wasteland.touko.moe/" target="_blank">Touko</a></li>
                <li class="btn btn-link"><a href="http://blog.slyli.cn/" target="_blank">SlyLi</a></li>
                <li class="btn btn-link"><a href="http://hjwblog.com/archives/" target="_blank">philhuan </a></li>
                <li class="btn btn-link"><a href="https://www.cnblogs.com/douzujun/" target="_blank">豆子</a></li>
                <li class="btn btn-link"><a href="http://zrawberry.com/article/article-content/35/You-Qing-Lian-Jie/">More</a></li>
            </ul>
        </div>
        <div class="col-md-12">
            <p>Copyright © 2020 <a href="/article/article-content/44/Guan-Yu-Kuai-Dao-Qie-Cao-Mei-Jun/">快刀切草莓君</a> | 互联网ICP备案：<a href="http://beian.miit.gov.cn/">闽ICP备18004703号-1</a></p>
        </div>
    </div>
</footer>

Zrawberry2020/templates/common/header.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-left" href="{% url 'index' %}">
                <img src="{% static '/image/logo3.png' %}" alt="logo"
                     style="margin-top: 8px; margin-right:5px;height: 30px;">
            </a>
            <a class="navbar-brand" href="{% url 'index' %}" style="font-family: 'font1'; font-size: 20px">Mr.Strawberry's
                House</a>


        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li {% if request.path|slice:"8" == '/article' %}class="active"{% endif %}><a
                        href="{% url 'article:article_titles' %}">文章</a></li>
                <li {% if request.path|slice:"11" == '/navigation' %}class="active"{% endif %}><a
                        href="{% url 'navigation:navigation_index' %}">网址导航</a></li>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                        aria-haspopup="true" aria-expanded="false">更多 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for link in nav_links %}
                            <li><a href="{{ link.link }}">{{ link.name }}</a></li>
                        {% empty %}
                            <li class="disabled"><a href="#">链接 未加载</a></li>
                        {% endfor %}
                        <li role="separator" class="divider"></li>
                        {% for page in special_page %}
                            <li><a href="{{ page.get_url_path }}">{{ page.title }}</a></li>
                        {% empty %}
                            <li class="disabled"><a href="#">特殊页 未加载</a></li>
                        {% endfor %}

                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown {{ account }}">
                        <a href="#"
                           class="dropdown-toggle {% if request.path|slice:"8" == '/account' %}active{% endif %}"
                           data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            {{ user.username }} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:dashboard' %}">用户后台</a></li>
                            <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:user_logout' %}">退出</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'account:user_register' %}">注册</a></li>
                    <li><a href="{% url 'account:user_login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

Zrawberry2020/templates/common/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'image/favicon2.ico' %}" type="image/x-icon"/>

    <title>草莓君的妙妙屋</title>

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
    <style>
        body {
            position: relative;
            background: url("{% static 'image/bg4.png' %}") no-repeat center 0;
            background-attachment: fixed;
            background-size: cover;
        }

        @font-face {
            font-family: 'font1';
            src: url("{% static 'fonts/ClastonScript.ttf' %}");
            font-style: normal;
            font-weight: normal;
        }

        h3 {
            color: #0a001f;
        }


        .nav li, .cover p {
            font-size: 21px;
        }


    </style>
</head>

<body>

<div class="site-wrapper">

    <div class="site-wrapper-inner">

        <div class="cover-container">

            <div class="masthead clearfix">
                <div class="inner">
                    <img class="masthead-brand" src="{% static 'image/logo3.png' %}"
                         style="margin-top:0px; margin-right: 3px; width: 35px">
                    <h3 class="masthead-brand" style="font-family: 'font1'">Mr.StrawberrY's House</h3>
                    <nav>
                        <ul class="nav masthead-nav">
                            <li><a href="{% url 'article:article_titles' %}">文章</a></li>
                            <li><a href="{% url 'navigation:navigation_index' %}">网址导航</a></li>
                            <li><a href="http://cloud.zrawberry.com">杂物间</a></li>
                            <li><a href="/article/article-content/44/Guan-Yu-Kuai-Dao-Qie-Cao-Mei-Jun/">关于</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>

            <div class="inner cover">
                <h1 class="cover-heading">欢迎来到草莓君的妙妙屋</h1>
                <br>
                <p class="lead">这里是快刀切草莓君的个人网站</p>
                <p class="lead">感受草莓君学习计算机的点点滴滴</p>
                <p class="lead">使用便捷的自定义网址导航服务</p>
                <p class="lead">
                    <a href="{% url 'article:article_titles' %}" class="btn btn-lg  btn-default">进入</a>
                </p>
            </div>

            <div class="mastfoot">
                <div class="inner">
                    <p>@2018-2020 草莓君的妙妙屋</p>
                    <p>互联网ICP备案：<a href="http://beian.miit.gov.cn/">闽ICP备18004703号-1</a></p>

                </div>
            </div>

        </div>
    </div>
</div>


<script src="{% static 'js/jquery.js' %}"></script>

</body>

</html>

Zrawberry2020/templates/common/paginator.html
<span class="current">

</span>



<nav aria-label="Page navigation" class="text-center">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="disabled">
                <a aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        <li><a>第{{ page_obj.number }}页 共{{ page_obj.paginator.num_pages }}页 </a></li>



        {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span
                        aria-hidden="true">&raquo;</span></a>
            </li>
        {% else %}
            <li class="disabled">
                <a aria-label="Next"><span
                        aria-hidden="true">&raquo;</span></a>
            </li>
        {% endif %}
    </ul>
</nav>