Zrawberry2020/Zrawberry2020/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from .sitemaps import BlogSitemap

sitemaps = {
    'blog': BlogSitemap,
}


urlpatterns = [
    path('', TemplateView.as_view(template_name='common/index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
    path('navigation/', include('navigation.urls', namespace='navigation')),
    path('images/', include('image.urls', namespace='images')),
    # robots, sitemap
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    # sitemaps should be a dictionary that maps a short section label (e.g., blog or news) to its Sitemap class
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Zrawberry2020/image/urls.py
from django.urls import path, re_path
from . import views

app_name = "images"

urlpatterns = [
    path('', views.PicList.as_view(), name='pic_list'),
    path('upload-modelform/', views.picture_modelform_upload, name='model_form_upload'),
    path('upload-ajax/', views.picture_ajax_upload, name='ajax_upload'),
    path('delete-ajax/', views.picture_delete, name='pic_delete'),
    re_path('pic/upload/$', views.PicUpload.as_view(), name='pic_upload'),
    re_path('pic/(?P<pk>\d+)/$', views.PicDetail.as_view(), name='pic_detail'),
]

Zrawberry2020/navigation/urls.py
from django.urls import path

from . import views

app_name = "navigation"

urlpatterns = [
    path('', views.FrontendView.as_view(), name="navigation_index"),
    path('navigation-link/', views.navigation_list, name="navigation_list"),
    path('navigation-box/', views.navigation_box, name="navigation_box"),
]

Zrawberry2020/navigation/models.py
from json import dumps
from collections import OrderedDict

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class LinkBox(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="LinkBox")
    boxname = models.CharField(max_length=20)
    urls = models.TextField(blank=True)
    created = models.DateField(default=timezone.now)

    def __str__(self):
        return self.boxname

    @staticmethod
    def dict_jsontr(urlds):
        if type(urlds) is dict:
            return dumps(urlds, sort_keys=True)
        elif type(urlds) is str:
            return eval(urlds)
        else:
            return None

    def str2dict(self):
        if self.urls:
            return eval(self.urls)
        else:
            return {}

    def urls_num(self):
        if self.urls:
            return len(self.str2dict())
        else:
            return 0

    class Meta:
        ordering = ('-created',)

Zrawberry2020/navigation/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import LinkBox


class LinkForm(forms.Form):
    sitename = forms.CharField(label="站点名")
    url = forms.URLField(label="网址")

Zrawberry2020/navigation/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView

from article.views import get_common_context
from .models import LinkBox
from .forms import LinkForm


@login_required
@csrf_exempt
def navigation_list(request):
    """盒子内的链接"""
    if request.method == 'GET':
        LBlist = LinkBox.objects.filter(owner=request.user).order_by('created')
        context = {
            'LBlist': LBlist,
            'LinkForm': LinkForm,
            'links': 'active',
        }
        get_common_context(context)
        return render(request, "navigation/back/nav_list.html", context=context)
    elif request.method == "POST":
        if request.POST['op'] == "add_url":
            # 添加链接
            box_id = request.POST['box_id']
            sitename = request.POST['sitename']
            url = request.POST['url']
            box = LinkBox.objects.get(owner_id=request.user.id, id=box_id)
            urldict = box.str2dict()
            # 检查是否已存在此站点
            if sitename in urldict.keys():
                return HttpResponse('2')
            else:
                urldict[sitename] = url
                box.urls = LinkBox.dict_jsontr(urldict)
                box.save()
                return HttpResponse('1')
        elif request.POST['op'] == "del_url":
            # 删除链接
            box_id = request.POST['box_id']
            sitename = request.POST['sitename']
            box = LinkBox.objects.get(owner_id=request.user.id, id=box_id)
            urldict = box.str2dict()
            try:
                urldict.pop(sitename)
                box.urls = LinkBox.dict_jsontr(urldict)
                box.save()
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        elif request.POST['op'] == 'update_url':
            # 修改链接
            box_id = request.POST['box_id']
            old_sitename = request.POST['old_sitename']
            new_sitename = request.POST['new_sitename']
            new_link = request.POST['url']
            box = LinkBox.objects.get(owner_id=request.user.id, id=box_id)
            urldict = box.str2dict()
            if old_sitename in urldict:
                del urldict[old_sitename]
                urldict[new_sitename] = new_link
                box.urls = LinkBox.dict_jsontr(urldict)
                box.save()
                return HttpResponse("1")
            else:
                return HttpResponse("2")
        else:
            return HttpResponse("2")


@login_required
@csrf_exempt
def navigation_box(request):
    if request.method == 'GET':
        LBlist = LinkBox.objects.filter(owner=request.user).order_by('created')
        context = {
            'LBlist': LBlist,
            'boxes': 'active',
        }
        get_common_context(context)
        return render(request, "navigation/back/nav_box.html", context=context)
    elif request.method == "POST":
        if request.POST['op'] == "add_box":
            # 添加盒子
            boxname = request.POST['boxname']
            if type(boxname) is str and len(boxname)>0:
                box = LinkBox(boxname=boxname, owner_id=request.user.id)
                box.save()
                return HttpResponse('1')
            else:
                return HttpResponse('2')
        elif request.POST['op'] == "del_box":
            # 删除盒子
            box_id = request.POST['boxid']
            box = LinkBox.objects.get(owner_id=request.user.id, id=box_id)
            try:
                box.delete()
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        elif request.POST['op'] == "update_box":
            # 修改盒子名称
            box_id = request.POST['boxid']
            boxname = request.POST['boxname']
            if type(boxname) is str and len(boxname)>0:
                box = LinkBox.objects.get(owner_id=request.user.id, id=box_id)
                box.boxname=boxname
                box.save()
                return HttpResponse('1')
            else:
                return HttpResponse('2')
        else:
            return HttpResponse("2")

def navigation_index(request):
    context = {}
    if request.user.is_authenticated:
        if hasattr(request.user, "LinkBox"):
            context['LBlist'] = request.user.LinkBox.all()
    get_common_context(context)
    return render(request, "navigation/front/nav_index.html", context=context)


class FrontendView(ListView):
    # template_name = "navigation/back/nav_box.html"
    template_name = "navigation/front/nav_index.html"
    context_object_name = 'LBlist'

    def get_queryset(self):
        # self.request.user
        if self.request.user.is_authenticated:
            # return LinkBox.objects.filter(owner=self.request.user).order_by('-created')
            return LinkBox.objects.filter(owner=self.request.user)
        else:
            return None

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        get_common_context(context)
        return context

Zrawberry2020/templates/navigation/back/nav_box.html
{% extends "common/back_base.html" %}

{% load static %}

{% block title %}
    网址导航管理
{% endblock %}

{% block content %}
    <form class="form-inline">
        <label><h4>站点类型（网址盒子）</h4></label>
        <button type="button" onclick="add_box()" class="btn btn-link">添加类型</button>
    </form>
    <table class="table table-hover">
        <thead>
        <tr>
            <td>序号</td>
            <td>名称</td>
            <td>链接数</td>
            <td>操作</td>
        </tr>
        </thead>
        {% for Box in LBlist %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ Box.boxname }}</td>
                <td>{{ Box.urls_num }}</td>
                <td>
                    <a name="delete" href="javascript:" onclick="del_box(this, {{ Box.id }})">
                        <span class="glyphicon glyphicon-trash"></span></a>&nbsp
                    <a name="update" href="javascript:" onclick="update_box(this, {{ Box.id }})">
                        <span class="glyphicon glyphicon-pencil"></span></a>
                </td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static "js/layer.js" %}"></script>
    <script type="text/javascript">
        function add_box() {
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "300px"],
                title: "新增盒子",
                content: '<div class="text-center" style="margin-top:20px"><label>盒子名</label>' +
                    '<input type="text" name="boxname" id="id_boxname">',
                btn: ['添加', '取消'],
                yes: function (index, layero) {
                    boxname = $('#id_boxname').val();
                    $.ajax({
                        url: '{% url "navigation:navigation_box" %}',
                        type: 'POST',
                        data: {"op": "add_box", "boxname": boxname},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                            } else {
                                layer.msg("添加失败")
                            }
                        },
                    });
                },
            });
        }

        function update_box(current, boxid) {
            var boxname = $(current).parents('tr').children('td').eq(1).text();
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "300px"],
                title: "修改盒子名称",
                content: '<div class="text-center" style="margin-top:20px"><label>盒子名</label>' +
                    '<input type="text" name="boxname" value="' + boxname + '" id="id_boxname">',
                btn: ['修改', '取消'],
                yes: function (index, layero) {
                    boxname = $('#id_boxname').val();
                    $.ajax({
                        url: '{% url "navigation:navigation_box" %}',
                        type: 'POST',
                        data: {"op": "update_box", "boxname": boxname, "boxid": boxid},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                            } else {
                                layer.msg("修改失败")
                            }
                        },
                    });
                },
            });
        }

        function del_box(current, boxid) {
            var boxname = $(current).parents('tr').children('td').eq(1).text();
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["300px", "150px"],
                title: "删除",
                content: '<p>删除盒子会一同删除盒子中的网址</p> <p>确认删除{' + boxname + '}?</p>',
                btn: ['确认', '取消'],
                yes: function (index, layero) {
                    $.ajax({
                        url: '{% url "navigation:navigation_box" %}',
                        type: 'POST',
                        data: {"op": "del_box", "boxid": boxid},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                            } else {
                                layer.msg("添加失败")
                            }
                        },
                    });
                },
            });
        }
    </script>
{% endblock %}

Zrawberry2020/templates/navigation/back/nav_list.html
{% extends "common/back_base.html" %}

{% load static %}

{% block title %}
    网址导航管理
{% endblock %}

{% block content %}
    <div>
        {% if LBlist %}
            {% for LB in LBlist %}
                <form class="form-inline">
                    <label><h4>{{ LB.boxname }}</h4></label>
                    <button type="button" onclick="add_url({{ LB.id }})"
                            class="btn btn-link">添加网址
                    </button>
                </form>
                <table class="table table-hover">
                    <tr>
                        <td>序号</td>
                        <td>站点名</td>
                        <td>网址</td>
                        <td>操作</td>
                    </tr>
                    {% for sitename,url in LB.str2dict.items %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ sitename }}</td>
                            <td><a href="{{ url }}">{{ url }}</a></td>
                            <td>
                                <a name="delete" href="javascript:" onclick="del_url(this, {{ LB.id }})">
                                <span class="glyphicon glyphicon-trash"></span>
                                </a>&nbsp
                                <a name="update" href="javascript:" onclick="update_url(this, {{ LB.id }})">
                                <span class="glyphicon glyphicon-pencil"></span>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            {% endfor %}
        {% else %}
            <h1>请先添加盒子！</h1>
            <p>盒子是站点存放的容器，先建立盒子然后再将站点添加到盒子内。</p>
        {% endif %}

    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static "js/layer.js" %}"></script>
    <script type="text/javascript">
        function add_url(boxid) {
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "300px"],
                title: "新增站点",
                content: '<div class="text-center" style="margin-top:20px"> ' +
                    '<label>{{ LinkForm.sitename.label }}</label> ' +
                    '<p>{{ LinkForm.sitename }}</p>' +
                    '<label>{{ LinkForm.url.label }}</label>' +
                    '<p>{{ LinkForm.url }}</p></div>',
                btn: ['添加', '取消'],
                yes: function (index, layero) {
                    sitename = $('#id_sitename').val();
                    siteurl = $('#id_url').val();
                    $.ajax({
                        url: '{% url "navigation:navigation_list" %}',
                        type: 'POST',
                        data: {"op": "add_url", "box_id": boxid, "sitename": sitename, "url": siteurl},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("添加成功");
                            } else {
                                layer.msg("添加失败")
                            }
                        },
                    });
                },
            });
        }

        function del_url(current, boxid) {
            var sitename = $(current).parents('tr').children('td').eq(1).text();
            $.ajax({
                url: '{% url "navigation:navigation_list" %}',
                type: "POST",
                data: {"op": "del_url", "box_id": boxid, "sitename": sitename},
                success: function (e) {
                    if (e == "1") {
                        parent.location.reload();
                    } else {
                        layer.msg("删除失败");
                    }
                },
            })
        }



        function update_url(current, boxid) {
            var sitename = $(current).parents('tr').children('td').eq(1).text();
            var link = $(current).parents('tr').children('td').eq(2).text();
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "300px"],
                title: "修改站点",
                content: '<div class="text-center" style="margin-top:20px"> ' +
                    '<label>{{ LinkForm.sitename.label }}</label> ' +
                    '<p><input type="text" name="sitename" required="True" value="'+ sitename +'" id="id_sitename"></p>' +
                    '<label>{{ LinkForm.url.label }}</label>' +
                    '<p><input type="url" name="url" required="" value="'+ link + '" id="id_url"></p></div>',
                btn: ['修改', '取消'],
                yes: function (index, layero) {
                    new_sitename = $('#id_sitename').val();
                    siteurl = $('#id_url').val();
                    $.ajax({
                        url: '{% url "navigation:navigation_list" %}',
                        type: 'POST',
                        data: {"op": "update_url", "box_id": boxid, "old_sitename": sitename, "new_sitename": new_sitename, "url": siteurl},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("修改成功");
                            } else {
                                layer.msg("修改失败")
                            }
                        },
                    });
                },
            });
        }

    </script>
{% endblock %}