Zrawberry2020/Zrawberry2020/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from .sitemaps import BlogSitemap

sitemaps = {
    'blog': BlogSitemap,
}


urlpatterns = [
    path('', TemplateView.as_view(template_name='common/index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
    path('navigation/', include('navigation.urls', namespace='navigation')),
    path('images/', include('image.urls', namespace='images')),
    # robots, sitemap
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    # sitemaps should be a dictionary that maps a short section label (e.g., blog or news) to its Sitemap class
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Zrawberry2020/image/urls.py
from django.urls import path, re_path
from . import views

app_name = "images"

urlpatterns = [
    path('', views.PicList.as_view(), name='pic_list'),
    path('upload-modelform/', views.picture_modelform_upload, name='model_form_upload'),
    path('upload-ajax/', views.picture_ajax_upload, name='ajax_upload'),
    path('delete-ajax/', views.picture_delete, name='pic_delete'),
    re_path('pic/upload/$', views.PicUpload.as_view(), name='pic_upload'),
    re_path('pic/(?P<pk>\d+)/$', views.PicDetail.as_view(), name='pic_detail'),
]

Zrawberry2020/image/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.urls import reverse
# from django.contrib.auth.models import User


# from slugify import slugify
from datetime import date
from uuid import uuid4
import os


def path_and_rename(instance, filename):
    upload_to = 'picture'
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)


class Picture(models.Model):
    title = models.CharField("标题", max_length=100, blank=True, default='')
    image = models.ImageField("图片", upload_to=path_and_rename, blank=True)
    date = models.DateField(default=date.today)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('images:pic_detail', args=[str(self.id)])


@receiver(post_delete, sender=Picture)
def delete_upload_images(sender, instance, **kwargs):
    image = getattr(instance, 'image', '')
    if not image:
        return
    imagename = os.path.join(settings.MEDIA_ROOT, str(image))
    if os.path.isfile(imagename):
        os.remove(imagename)

Zrawberry2020/image/forms.py
from django import forms
from django.core.files.base import ContentFile

from .models import Picture


class PictureUploadForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ('title', 'image',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def clean_file(self):
        image = self.cleaned_data['image']
        ext = image.name.split('.')[-1].lower()
        if ext not in ['jpg', 'png']:
            raise forms.ValidationError("仅支持jpg和png")

        return image

Zrawberry2020/article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.utils import timezone

from .models import ArticleColumn, ArticlePost, ArticleTag, Navlink
from .forms import ArticleColumnForm, ArticlePostForm, CommentForm


def get_common_context(context):
    context.update(ArticlePost.get_special_page())
    context.update(Navlink.get_nav_link())

# == 文章栏目 ==
# @permission_required()
@login_required
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        context = {
            "columns": columns,
            "column_form": column_form,
            "column": 'active',
        }
        get_common_context(context)
        return render(request, "article/column/article_column.html", context=context)

    elif request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        # 检查是否已经存在该栏目
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")


@login_required()
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required()
@require_POST
@csrf_exempt
def delete_article_column(request):
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


# == 文章编辑 ==
class ArticlePostView(CreateView):
    """文章发布"""
    model = ArticlePost
    # title, column, body, showtype,targetuser
    fields = ['title', 'column', 'showtype', 'targetuser', 'body', 'tags']
    template_name = 'article/column/article_post.html'

    def form_valid(self, form):
        if self.request.user.has_perm('article.post_article'):
            # 只有拥有发布权限才指定 user
            form.instance.author = self.request.user
        else:
            raise Http404("Poll does not exist")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ArticlePostView, self).get_context_data(**kwargs)
        context['post'] = 'active'
        get_common_context(context)
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ArticlePostView, self).dispatch(request, *args, **kwargs)


class ArticleEditView(UpdateView):
    """文章编辑"""
    model = ArticlePost
    fields = ['title', 'column', 'showtype', 'targetuser', 'body', 'tags']
    template_name = 'article/column/article_post.html'
    context_object_name = 'article_form'
    # template_name_suffix = '_update_form'

    def form_valid(self, form):
        form.instance.updated = timezone.now()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ArticleEditView, self).get_context_data(**kwargs)
        context['post'] = 'active'
        get_common_context(context)
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ArticleEditView, self).dispatch(request, *args, **kwargs)


@login_required()
def article_list(request):
    # articles = ArticlePost.objects.filter(author=request.user)
    # return render(request, "article/column/article_list.html", {"articles": articles})
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 14)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    context = {
        "articles": articles,
        "page_obj": current_page,
        "list": 'active',
    }
    get_common_context(context)
    return render(request, "article/column/article_list.html", context=context)


@login_required()
def article_detail(request, id, slug):
    """从链接中获取文章信息"""
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    context = {"article":article}
    get_common_context(context)
    return render(request, "article/column/article_detail.html", context=context)


@login_required()
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


def article_titles(request, column_name=None):
    # articles = User.objects.get(id=1).article.filter(showtype='0')  # 只展示Zachary的
    articles = ArticlePost.objects.filter(showtype='0')
    if request.GET.get('search', None):
        articles = articles.filter(title__contains=request.GET['search'])
    # 获取文章列表
    if column_name:
        try:
            # articles_title = ArticleColumn.objects.get(column=column_name).article.all()
            # articles_title = ArticleColumn.objects.get(column=column_name).article.all()
            column = ArticleColumn.objects.get(column=column_name)
            articles_title = articles.filter(column=column)
        except:
            return HttpResponseRedirect(reverse('article:article_titles'))
    else:
        articles_title = articles

    # 文章分页
    paginator = Paginator(articles_title, 3)
    page_number = request.GET.get('page')
    # try:
    #     current_page = paginator.page(page_number)
    #     articles = current_page.object_list
    try:
        page_obj = paginator.get_page(page_number)
        articles = page_obj.object_list
    except PageNotAnInteger:
        page_obj = paginator.get_page(1)
        articles = page_obj.object_list
    except EmptyPage:
        page_obj = paginator.get_page(paginator.num_pages)
        articles = page_obj.object_list

    # 获取分类列表
    # columns = User.objects.get(id=1).article_column.all()
    columns = ArticleColumn.objects.all()
    context = {
        "articles": articles,
        "page_obj": page_obj,
        "columns": columns,
        "search": request.GET.get('search', None),
    }
    if column_name:
        context['active'] = column_name
    get_common_context(context)
    return render(request, "article/front/article_titles.html", context=context)


def article_content(request, aid, slug):
    """文章内容"""
    article = get_object_or_404(ArticlePost, id=aid, slug=slug)
    context = {
        "article": article,
    }
    # 特殊类型文章
    if article.showtype == '1':
        if request.user == 'AnonymousUser' or not request.user.has_perm('article.get_dessert'):
            return HttpResponseRedirect(reverse('account:user_login')+'?next='+request.path)
        if request.method == "POST":  # 仅特殊文章可以评论
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.article = article
                new_comment.commentator = request.user
                new_comment.save()
            else:
                return render(request, "404.html")
        else:
            comment_form = CommentForm()

        context['form'] = comment_form
        context['comment'] = True

    if request.user.id != 1:
        article.viewed += 1
    article.save()
    get_common_context(context)
    return render(request, "article/front/article_content.html", context=context)


@login_required
@permission_required('article.get_dessert', raise_exception=True)
def dessert(request):
    """甜品站titles"""
    # articles = User.objects.get(id=1).article.filter(showtype='1')
    articles = ArticlePost.objects.filter(showtype='1')

    articles_title = articles.filter(targetuser=request.user)
    paginator = Paginator(articles_title, 3)
    page = request.GET.get('page')

    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    # 获取分类列表
    # columns = User.objects.get(id=1).article_column.all()
    columns = ArticleColumn.objects.all()
    context = {
        "articles": articles,
        "page_obj": current_page,
        "columns": columns,
    }
    get_common_context(context)
    return render(request, "article/front/article_titles.html", context=context)


class TimelineView(ListView):
    model = ArticlePost
    queryset = ArticlePost.objects.filter(showtype='0').order_by("-created")
    template_name = "article/front/article_timeline.html"
    context_object_name = 'articles'

    def get_context_data(self, **kwargs):
        context = super(TimelineView, self).get_context_data(**kwargs)

Zrawberry2020/image/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.views.decorators.http import require_POST
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView
from django.urls import reverse
from django.template.defaultfilters import filesizeformat
from django.contrib.auth.decorators import login_required

from .models import Picture
from .forms import PictureUploadForm


class PicList(ListView):
    queryset = Picture.objects.all().order_by('-date')
    # ListView默认Context_object_name是object_list
    context_object_name = 'picture_list'
    # 默认template_name = 'pic_upload/picture_list.html'
    template_name = 'image/back/image_manage.html'

    paginate_by = 6

    form = PictureUploadForm
    extra_context = {
        'form': form,
        'pic': 'active',
    }


class PicDetail(DetailView):
    model = Picture
    # DetailView默认Context_object_name是picture

    # 下面是DetailView默认模板，可以换成自己的
    template_name = 'image/test/picture_detail.html'


# 视图
class PicUpload(CreateView):
    model = Picture

    # 可以通过fields选项自定义需要显示的表单
    fields = ['title', 'image']

    # CreateView默认Context_object_name是form。

    # 下面是CreateView默认模板，可以换成自己模板
    template_name = 'image/test/picture_form.html'


# 使用modelform上传
def picture_modelform_upload(requset):
    if requset.method == "POST":
        form = PictureUploadForm(requset.POST, requset.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('images:pic_list'))
    else:
        form = PictureUploadForm()
        context = {
            'form': form,
        }

    return render(requset, 'image/back/image_manage.html', context=context)


@login_required
@require_POST
def picture_ajax_upload(request):
    form = PictureUploadForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        pictures = Picture.objects.all().order_by('-id')
        data = []
        for pic in pictures:
            data.append(
                {"title": pic.title,
                 "url": pic.image.url,
                 "size": filesizeformat(pic.image.size),
                 "date": pic.date,
                 }
            )
        return JsonResponse(data, safe=False)
    else:
        data = {'error_msg': '仅支持jpg, png格式'}
        return JsonResponse(data)



@login_required
@require_POST
def picture_delete(request):
    try:
        image_id = request.POST['image_id']
        pic = Picture.objects.get(id=image_id)
        pic.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

Zrawberry2020/templates/image/back/image_manage.html
{% extends "common/back_base.html" %}

{% load static %}

{% block title %}
    图片
{% endblock %}

{% block content %}
    <h3>图片列表</h3>
    {% if picture_list %}
        <table class="table table-hover" id="result">
            <tbody>
            <tr>
                <td>文件名</td>
                <td>文件大小</td>
                <td>上传日期</td>
                <td>操作</td>
            </tr>
            {% for picture in picture_list %}
                <tr>
                    <td><a href="{{ picture.image.url }}">{{ picture.title }}</a></td>
                    <td>{{ picture.image.size | filesizeformat }}</td>
                    <td>{{ picture.date| date:"Y-m-j" }}</td>
                    <td><a name="delete" href="javascript:" onclick="del_image(this,{{ picture.id }})">
                        <span class="glyphicon glyphicon-trash" style="margin-left:20px"></span></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <li>还没有上传新图片</li>
    {% endif %}

    {% include "common/paginator.html" %}

    <h3>上传图片</h3>
    <form action="" method="post" enctype="multipart/form-data" id="form">
        <ul class="errorlist"></ul>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="button" class="btn btn-default" value="ajax上传" id="btn"/>
    </form>



{% endblock %}

{% block javascript %}
    <script src=" https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script>
        var csrftoken = $.cookie('csrftoken');

        function csrfSafeMethod(method) {
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $(document).ready(function () {
            $('#btn').click(function (e) {
                e.preventDefault();
                // 构建FormData对象
                var form_data = new FormData();
                form_data.append('image', $('#id_image')[0].files[0]);
                form_data.append('title', $('#id_title').val());
                $.ajax({
                    url: '{% url 'images:ajax_upload' %}',
                    data: form_data,
                    type: 'POST',
                    dataType: 'json',
                    // 告诉jQuery不要去处理发送的数据, 发送对象。
                    processData: false,
                    // 告诉jQuery不要去设置Content-Type请求头
                    contentType: false,
                    // 获取POST所需的csrftoken
                    beforeSend: function (xhr, settings) {
                        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    },
                    success: function (data) {
                        if (data['error_msg']) {
                            var content = data['error_msg'];
                            $('ul.errorlist').html(content);
                        }
                        else {
                            var content = '<tbody><tr>' +
                                '<th>文件名</th>' +
                                '<th>文件大小</th>' +
                                '<th>上传日期</th>' +
                                '</tr>';
                            $.each(data, function (i, item) {
                                content = content +
                                    '<tr><td>' +
                                    "<a href= ' " +
                                    item['url'] +
                                    " '> " +
                                    item['title'] +
                                    '</a></td><td>' +
                                    item['size'] +
                                    '</td><td>' +
                                    item['date'] +
                                    '</td><tr>'
                            });
                            content = content + "</tbody>";
                            // $('#result').html(content);
                            location.reload()
                        }
                    },
                });
            });
        });

        function del_image(the, image_id) {
            alert(image_id);
            $.ajax({
                url: "{% url 'images:pic_delete' %}",
                type: "POST",
                data: {"image_id": image_id},
                // 获取POST所需的csrftoken
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                },
                success: function (e) {
                    if (e == "1") {
                        layer.msg("删除成功");
                        location.reload();
                    } else {
                        layer.msg("删除失败");
                    }
                },
            })
        }


    </script>
{% endblock %}